export const RESTAURANT_TYPES = [
  "Nhà hàng",
  "Quán ăn nhỏ",
  "Nhà hàng Việt Nam",
  "Nhà hàng Trung Quốc",
  "Nhà hàng Hàn Quốc",
  "Nhà hàng Nhật Bản",
  "Nhà hàng Thái Lan",
];

export const ADVANCED_FILTERS: Record<string, string[]> = {
  phu_hop_cho_nguoi_khuyet_tat: [
    "Vòng trợ thính",
    "Nhà vệ sinh cho xe lăn",
    "Chỗ ngồi cho xe lăn",
    "Chỗ đỗ xe cho xe lăn",
    "Lối vào cho xe lăn",
  ],
  cac_tuy_chon_dich_vu: [
    "Dịch vụ tại chỗ",
    "Ăn tại chỗ",
    "Chỗ ngồi ngoài trời",
    "Đồ ăn mang đi",
    "Mua hàng ngay trên xe",
    "Giao hàng",
    "Giao hàng gián tiếp",
  ],
  diem_noi_bat: [
    "Chỗ ngồi trên sân thượng",
    "Thể thao",
    "Nhiều trà ngon",
    "Nhiều rượu vang ngon",
    "Món tráng miệng ngon",
    "Cà phê ngon",
    "Nhạc sống",
    "Rượu cốc tai ngon",
    "Lò sưởi",
    "Nhiều bia ngon",
  ],
  noi_tieng_ve: ["Bữa trưa", "Bữa tối", "Bữa sáng", "Ăn tối một mình"],
  dich_vu: [
    "Đồ uống vào giờ vàng",
    "Các món chay",
    "Nhà hàng thức ăn nhanh",
    "Các món tốt cho sức khoẻ",
    "Các món thuần chay",
    "Có giờ giảm giá đặc biệt",
    "Ăn thoả thích",
    "Rượu mạnh",
    "Rượu",
    "Thực đơn chữ nổi",
    "Bia",
    "Cà phê",
    "Đồ ăn khuya",
    "Đồ ăn cho người theo đạo Hồi",
    "Phòng ăn riêng tư",
    "Rượu cốc tai",
    "Món ăn từ nguyên liệu hữu cơ",
    "Rượu vang",
    "Quầy rau trộn",
    "Phần ăn nhỏ",
  ],
  lua_chon_an_uong: [
    "Chỗ ngồi",
    "Phục vụ tại bàn",
    "Bữa nửa buổi",
    "Dịch vụ ăn uống",
    "Bữa trưa",
    "Dịch vụ tại quầy",
    "Bữa tối",
    "Bữa sáng",
    "Món tráng miệng",
  ],
  tien_nghi: [
    "Quầy bar tại chỗ",
    "Nhà vệ sinh cho cả hai giới",
    "Wi-Fi miễn phí",
    "Nhà vệ sinh",
    "Wi-Fi",
  ],
  bau_khong_khi: [
    "Yên tĩnh",
    "Thông thường",
    "Sành điệu",
    "Lãng mạn",
    "Ấm cúng",
    "Cao cấp",
  ],
  khach_hang: [
    "Du khách",
    "Chào đón những người thuộc giới LGBTQ+",
    "Sinh viên",
    "Dành cho gia đình",
    "Nhóm",
    "Nơi an toàn cho người chuyển giới",
  ],
  len_ke_hoach: [
    "Nên đặt chỗ ăn tối trước",
    "Bắt buộc đặt chỗ trước",
    "Thường phải đợi",
    "Ghé nhanh",
    "Nên đặt chỗ bữa nửa buổi trước",
    "Nên đặt chỗ ăn trưa trước",
    "Nhận đặt chỗ",
  ],
  thanh_toan: [
    "Séc",
    "Thanh toán di động qua NFC",
    "Chỉ nhận tiền mặt",
    "Thẻ tín dụng",
    "Thẻ ghi nợ",
  ],
  tre_em: [
    "Ghế cao cho bé",
    "Thực đơn dành cho trẻ em",
    "Sân chơi",
    "Có bàn thay tã, bỉm",
    "Phù hợp cho trẻ em",
    "Phù hợp cho tiệc sinh nhật của trẻ em",
  ],
  bai_do_xe: [
    "Chỗ đỗ xe trong khuôn viên",
    "Bãi đỗ xe miễn phí",
    "Đỗ xe miễn phí trên đường",
    "Gara đỗ xe có tính phí",
    "Gara đỗ xe miễn phí",
    "Bãi đỗ xe có tính phí",
    "Nhiều chỗ đỗ xe",
    "Dịch vụ đỗ xe",
    "Hơi khó tìm chỗ đỗ xe",
    "Đỗ xe có tính phí trên đường",
  ],
  tu_doanh_nghiep: ["Tự nhận là do phụ nữ sở hữu"],
  thu_cung: [
    "Cho phép mang theo chó",
    "Được mang chó vào trong",
    "Cho phép mang theo chó bên ngoài",
  ],
};