// import { Restaurant } from "@/types/restaurant";

// export const MOCK_RESTAURANTS: Restaurant[] = [
//   {
//     id: "1",
//     name: "Bangkok Street 55",
//     category: "Nhà hàng Thái Lan",
//     priceLevel: "$$",
//     averagePrice: 120000,
//     rating: 4.6,
//     address: "123 Trần Hưng Đạo, Quận 5, TP.HCM",
//     phone: "0901 111 222",
//     openingStatus: "Đang mở cửa",
//     image:
//       "https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80",
//     tags: ["Thái Lan", "Mở cửa", "Ăn tại chỗ", "Wi-Fi"],
//     lgbtFriendly: true,
//     reviews: [
//       {
//         id: "r1",
//         author: "An",
//         time: "2 ngày trước",
//         rating: 5,
//         comment: "Món ăn đậm vị, nhân viên dễ thương, lên món khá nhanh.",
//       },
//       {
//         id: "r2",
//         author: "Bình",
//         time: "5 ngày trước",
//         rating: 4,
//         comment: "Không gian ổn, pad thai ngon, giá hơi cao một chút.",
//       },
//       {
//         id: "r3",
//         author: "Chi",
//         time: "1 tuần trước",
//         rating: 3,
//         comment: "Cuối tuần đông nên phải đợi bàn hơi lâu.",
//       },
//     ],
//     peakHours: [
//       { hour: "8h", value: 20 },
//       { hour: "10h", value: 35 },
//       { hour: "12h", value: 90 },
//       { hour: "14h", value: 55 },
//       { hour: "16h", value: 40 },
//       { hour: "18h", value: 95 },
//       { hour: "20h", value: 80 },
//       { hour: "22h", value: 30 },
//     ],
//     sentimentSummary: [
//       { name: "Tốt", value: 68 },
//       { name: "Trung bình", value: 22 },
//       { name: "Dở", value: 10 },
//     ],
//     sentimentTimeline: [
//       { period: "T1", tot: 12, trungBinh: 5, do: 2 },
//       { period: "T2", tot: 16, trungBinh: 4, do: 1 },
//       { period: "T3", tot: 18, trungBinh: 6, do: 2 },
//       { period: "T4", tot: 14, trungBinh: 5, do: 3 },
//     ],
//   },
//   {
//     id: "2",
//     name: "Tiệm mì Hoa Viên",
//     category: "Nhà hàng Trung Quốc",
//     priceLevel: "$",
//     averagePrice: 70000,
//     rating: 4.3,
//     address: "45 Nguyễn Trãi, Quận 5, TP.HCM",
//     phone: "0902 333 444",
//     openingStatus: "Sắp đóng cửa",
//     image:
//       "https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80",
//     tags: ["Trung Quốc", "Mì", "Bữa trưa", "Mang đi"],
//     lgbtFriendly: false,
//     reviews: [
//       {
//         id: "r4",
//         author: "Dũng",
//         time: "1 ngày trước",
//         rating: 4,
//         comment: "Sợi mì ngon, nước dùng đậm đà, phần ăn khá đầy.",
//       },
//       {
//         id: "r5",
//         author: "Hà",
//         time: "3 ngày trước",
//         rating: 5,
//         comment: "Giá tốt, hợp ăn trưa nhanh.",
//       },
//     ],
//     peakHours: [
//       { hour: "8h", value: 10 },
//       { hour: "10h", value: 25 },
//       { hour: "12h", value: 85 },
//       { hour: "14h", value: 50 },
//       { hour: "16h", value: 20 },
//       { hour: "18h", value: 60 },
//       { hour: "20h", value: 40 },
//       { hour: "22h", value: 15 },
//     ],
//     sentimentSummary: [
//       { name: "Tốt", value: 60 },
//       { name: "Trung bình", value: 30 },
//       { name: "Dở", value: 10 },
//     ],
//     sentimentTimeline: [
//       { period: "T1", tot: 8, trungBinh: 5, do: 1 },
//       { period: "T2", tot: 10, trungBinh: 4, do: 2 },
//       { period: "T3", tot: 11, trungBinh: 6, do: 1 },
//       { period: "T4", tot: 12, trungBinh: 5, do: 2 },
//     ],
//   },
//   {
//     id: "3",
//     name: "Nhà hàng Việt Sen",
//     category: "Nhà hàng Việt Nam",
//     priceLevel: "$$$",
//     averagePrice: 250000,
//     rating: 4.8,
//     address: "200 Châu Văn Liêm, Quận 5, TP.HCM",
//     phone: "0909 888 999",
//     openingStatus: "Đang mở cửa",
//     image:
//       "https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80",
//     tags: ["Việt Nam", "Cao cấp", "Gia đình", "Đặt chỗ"],
//     lgbtFriendly: true,
//     reviews: [
//       {
//         id: "r6",
//         author: "Lan",
//         time: "Hôm qua",
//         rating: 5,
//         comment: "Không gian đẹp, phù hợp đi cùng gia đình hoặc tiếp khách.",
//       },
//     ],
//     peakHours: [
//       { hour: "8h", value: 12 },
//       { hour: "10h", value: 18 },
//       { hour: "12h", value: 70 },
//       { hour: "14h", value: 35 },
//       { hour: "16h", value: 30 },
//       { hour: "18h", value: 88 },
//       { hour: "20h", value: 92 },
//       { hour: "22h", value: 28 },
//     ],
//     sentimentSummary: [
//       { name: "Tốt", value: 76 },
//       { name: "Trung bình", value: 18 },
//       { name: "Dở", value: 6 },
//     ],
//     sentimentTimeline: [
//       { period: "T1", tot: 15, trungBinh: 4, do: 1 },
//       { period: "T2", tot: 18, trungBinh: 3, do: 1 },
//       { period: "T3", tot: 21, trungBinh: 4, do: 1 },
//       { period: "T4", tot: 19, trungBinh: 5, do: 1 },
//     ],
//   },
// ];